import {
  WidthType,
  MinWidthType,
  MaxWidthType,
  HeightType,
  MinHeightType,
  MaxHeightType
} from "config/tailwind-type";

export const Width: AttributeProps = {
  type: WidthType.toString(),
  header: "Width 属性",
  title: "Width ClassName：",
  inputPlaceholder: "width: xxxx",
  selectPlaceholder: "width: xxxx",
  hasCustom: true,
  options: [
    { value: "w-0", label: "width: 0px;" },
    { value: "w-px", label: "width: 1px;" },
    { value: "w-0.5", label: "width: 0.125rem; /* 2px */" },
    { value: "w-1", label: "width: 0.25rem; /* 4px */" },
    { value: "w-1.5", label: "width: 0.375rem; /* 6px */" },
    { value: "w-2", label: "width: 0.5rem; /* 8px */" },
    { value: "w-2.5", label: "width: 0.625rem; /* 10px */" },
    { value: "w-3", label: "width: 0.75rem; /* 12px */" },
    { value: "w-3.5", label: "width: 0.875rem; /* 14px */" },
    { value: "w-4", label: "width: 1rem; /* 16px */" },
    { value: "w-5", label: "width: 1.25rem; /* 20px */" },
    { value: "w-6", label: "width: 1.5rem; /* 24px */" },
    { value: "w-7", label: "width: 1.75rem; /* 28px */" },
    { value: "w-8", label: "width: 2rem; /* 32px */" },
    { value: "w-9", label: "width: 2.25rem; /* 36px */" },
    { value: "w-10", label: "width: 2.5rem; /* 40px */" },
    { value: "w-11", label: "width: 2.75rem; /* 44px */" },
    { value: "w-12", label: "width: 3rem; /* 48px */" },
    { value: "w-14", label: "width: 3.5rem; /* 56px */" },
    { value: "w-16", label: "width: 4rem; /* 64px */" },
    { value: "w-20", label: "width: 5rem; /* 80px */" },
    { value: "w-24", label: "width: 6rem; /* 96px */" },
    { value: "w-28", label: "width: 7rem; /* 112px */" },
    { value: "w-32", label: "width: 8rem; /* 128px */" },
    { value: "w-36", label: "width: 9rem; /* 144px */" },
    { value: "w-40", label: "width: 10rem; /* 160px */" },
    { value: "w-44", label: "width: 11rem; /* 176px */" },
    { value: "w-48", label: "width: 12rem; /* 192px */" },
    { value: "w-52", label: "width: 13rem; /* 208px */" },
    { value: "w-56", label: "width: 14rem; /* 224px */" },
    { value: "w-60", label: "width: 15rem; /* 240px */" },
    { value: "w-64", label: "width: 16rem; /* 256px */" },
    { value: "w-72", label: "width: 18rem; /* 288px */" },
    { value: "w-80", label: "width: 20rem; /* 320px */" },
    { value: "w-96", label: "width: 24rem; /* 384px */" },
    { value: "w-auto", label: "width: auto;" },
    { value: "w-1/2", label: "width: 50%;" },
    { value: "w-1/3", label: "width: 33.333333%;" },
    { value: "w-2/3", label: "width: 66.666667%;" },
    { value: "w-1/4", label: "width: 25%;" },
    { value: "w-2/4", label: "width: 50%;" },
    { value: "w-3/4", label: "width: 75%;" },
    { value: "w-1/5", label: "width: 20%;" },
    { value: "w-2/5", label: "width: 40%;" },
    { value: "w-3/5", label: "width: 60%;" },
    { value: "w-4/5", label: "width: 80%;" },
    { value: "w-1/6", label: "width: 16.666667%;" },
    { value: "w-2/6", label: "width: 33.333333%;" },
    { value: "w-3/6", label: "width: 50%;" },
    { value: "w-4/6", label: "width: 66.666667%;" },
    { value: "w-5/6", label: "width: 83.333333%;" },
    { value: "w-1/12", label: "width: 8.333333%;" },
    { value: "w-2/12", label: "width: 16.666667%;" },
    { value: "w-3/12", label: "width: 25%;" },
    { value: "w-4/12", label: "width: 33.333333%;" },
    { value: "w-5/12", label: "width: 41.666667%;" },
    { value: "w-6/12", label: "width: 50%;" },
    { value: "w-7/12", label: "width: 58.333333%;" },
    { value: "w-8/12", label: "width: 66.666667%;" },
    { value: "w-9/12", label: "width: 75%;" },
    { value: "w-10/12", label: "width: 83.333333%;" },
    { value: "w-11/12", label: "width: 91.666667%;" },
    { value: "w-full", label: "width: 100%;" },
    { value: "w-screen", label: "width: 100vw;" },
    { value: "w-min", label: "width: min-content;" },
    { value: "w-max", label: "width: max-content;" },
    { value: "w-fit", label: "width: fit-content;" }
  ]
};

export const MinWidth: AttributeProps = {
  type: MinWidthType.toString(),
  header: "Min-Width 属性",
  title: "Min-Width ClassName：",
  inputPlaceholder: "min-width: xxxx",
  selectPlaceholder: "min-width: xxxx",
  hasCustom: true,
  options: [
    { value: "min-w-0", label: "min-width: 0px;" },
    { value: "min-w-full", label: "min-width: 100%;" },
    { value: "min-w-min", label: "min-width: min-content;" },
    { value: "min-w-max", label: "min-width: max-content;" },
    { value: "min-w-fit", label: "min-width: fit-content;" }
  ]
};

export const MaxWidth: AttributeProps = {
  type: MaxWidthType.toString(),
  header: "Max-Width 属性",
  title: "Max-Width ClassName：",
  inputPlaceholder: "max-width: xxxx",
  selectPlaceholder: "max-width: xxxx",
  hasCustom: true,
  options: [
    { value: "max-w-0", label: "max-width: 0rem; /* 0px */" },
    { value: "max-w-none", label: "max-width: none;" },
    { value: "max-w-xs", label: "max-width: 20rem; /* 320px */" },
    { value: "max-w-sm", label: "max-width: 24rem; /* 384px */" },
    { value: "max-w-md", label: "max-width: 28rem; /* 448px */" },
    { value: "max-w-lg", label: "max-width: 32rem; /* 512px */" },
    { value: "max-w-xl", label: "max-width: 36rem; /* 576px */" },
    { value: "max-w-2xl", label: "max-width: 42rem; /* 672px */" },
    { value: "max-w-3xl", label: "max-width: 48rem; /* 768px */" },
    { value: "max-w-4xl", label: "max-width: 56rem; /* 896px */" },
    { value: "max-w-5xl", label: "max-width: 64rem; /* 1024px */" },
    { value: "max-w-6xl", label: "max-width: 72rem; /* 1152px */" },
    { value: "max-w-7xl", label: "max-width: 80rem; /* 1280px */" },
    { value: "max-w-full", label: "max-width: 100%;" },
    { value: "max-w-min", label: "max-width: min-content;" },
    { value: "max-w-max", label: "max-width: max-content;" },
    { value: "max-w-fit", label: "max-width: fit-content;" },
    { value: "max-w-prose", label: "max-width: 65ch;" },
    { value: "max-w-screen-sm", label: "max-width: 640px;" },
    { value: "max-w-screen-md", label: "max-width: 768px;" },
    { value: "max-w-screen-lg", label: "max-width: 1024px;" },
    { value: "max-w-screen-xl", label: "max-width: 1280px;" },
    { value: "max-w-screen-2xl", label: "max-width: 1536px;" }
  ]
};

export const Height: AttributeProps = {
  type: HeightType.toString(),
  header: "Height 属性",
  title: "Height ClassName：",
  inputPlaceholder: "height: xxxx",
  selectPlaceholder: "height: xxxx",
  hasCustom: true,
  options: [
    { value: "h-0", label: "height: 0px;" },
    { value: "h-px", label: "height: 1px;" },
    { value: "h-0.5", label: "height: 0.125rem; /* 2px */" },
    { value: "h-1", label: "height: 0.25rem; /* 4px */" },
    { value: "h-1.5", label: "height: 0.375rem; /* 6px */" },
    { value: "h-2", label: "height: 0.5rem; /* 8px */" },
    { value: "h-2.5", label: "height: 0.625rem; /* 10px */" },
    { value: "h-3", label: "height: 0.75rem; /* 12px */" },
    { value: "h-3.5", label: "height: 0.875rem; /* 14px */" },
    { value: "h-4", label: "height: 1rem; /* 16px */" },
    { value: "h-5", label: "height: 1.25rem; /* 20px */" },
    { value: "h-6", label: "height: 1.5rem; /* 24px */" },
    { value: "h-7", label: "height: 1.75rem; /* 28px */" },
    { value: "h-8", label: "height: 2rem; /* 32px */" },
    { value: "h-9", label: "height: 2.25rem; /* 36px */" },
    { value: "h-10", label: "height: 2.5rem; /* 40px */" },
    { value: "h-11", label: "height: 2.75rem; /* 44px */" },
    { value: "h-12", label: "height: 3rem; /* 48px */" },
    { value: "h-14", label: "height: 3.5rem; /* 56px */" },
    { value: "h-16", label: "height: 4rem; /* 64px */" },
    { value: "h-20", label: "height: 5rem; /* 80px */" },
    { value: "h-24", label: "height: 6rem; /* 96px */" },
    { value: "h-28", label: "height: 7rem; /* 112px */" },
    { value: "h-32", label: "height: 8rem; /* 128px */" },
    { value: "h-36", label: "height: 9rem; /* 144px */" },
    { value: "h-40", label: "height: 10rem; /* 160px */" },
    { value: "h-44", label: "height: 11rem; /* 176px */" },
    { value: "h-48", label: "height: 12rem; /* 192px */" },
    { value: "h-52", label: "height: 13rem; /* 208px */" },
    { value: "h-56", label: "height: 14rem; /* 224px */" },
    { value: "h-60", label: "height: 15rem; /* 240px */" },
    { value: "h-64", label: "height: 16rem; /* 256px */" },
    { value: "h-72", label: "height: 18rem; /* 288px */" },
    { value: "h-80", label: "height: 20rem; /* 320px */" },
    { value: "h-96", label: "height: 24rem; /* 384px */" },
    { value: "h-auto", label: "height: auto;" },
    { value: "h-1/2", label: "height: 50%;" },
    { value: "h-1/3", label: "height: 33.333333%;" },
    { value: "h-2/3", label: "height: 66.666667%;" },
    { value: "h-1/4", label: "height: 25%;" },
    { value: "h-2/4", label: "height: 50%;" },
    { value: "h-3/4", label: "height: 75%;" },
    { value: "h-1/5", label: "height: 20%;" },
    { value: "h-2/5", label: "height: 40%;" },
    { value: "h-3/5", label: "height: 60%;" },
    { value: "h-4/5", label: "height: 80%;" },
    { value: "h-1/6", label: "height: 16.666667%;" },
    { value: "h-2/6", label: "height: 33.333333%;" },
    { value: "h-3/6", label: "height: 50%;" },
    { value: "h-4/6", label: "height: 66.666667%;" },
    { value: "h-5/6", label: "height: 83.333333%;" },
    { value: "h-full", label: "height: 100%;" },
    { value: "h-screen", label: "height: 100vh;" },
    { value: "h-min", label: "height: min-content;" },
    { value: "h-max", label: "height: max-content;" },
    { value: "h-fit", label: "height: fit-content;" }
  ]
};

export const MinHeight: AttributeProps = {
  type: MinHeightType.toString(),
  header: "Min-Height 属性",
  title: "Min-Height ClassName：",
  inputPlaceholder: "min-height: xxxx",
  selectPlaceholder: "min-height: xxxx",
  hasCustom: true,
  options: [
    { value: "min-h-0", label: "min-height: 0px;" },
    { value: "min-h-full", label: "min-height: 100%;" },
    { value: "min-h-screen", label: "min-height: 100vh;" },
    { value: "min-h-min", label: "min-height: min-content;" },
    { value: "min-h-max", label: "min-height: max-content;" },
    { value: "min-h-fit", label: "min-height: fit-content;" }
  ]
};

export const MaxHeight: AttributeProps = {
  type: MaxHeightType.toString(),
  header: "Max-Height 属性",
  title: "Max-Height ClassName：",
  inputPlaceholder: "max-height: xxxx",
  selectPlaceholder: "max-height: xxxx",
  hasCustom: true,
  options: [
    { value: "max-h-0", label: "max-height: 0px;" },
    { value: "max-h-px", label: "max-height: 1px;" },
    { value: "max-h-0.5", label: "max-height: 0.125rem; /* 2px */" },
    { value: "max-h-1", label: "max-height: 0.25rem; /* 4px */" },
    { value: "max-h-1.5", label: "max-height: 0.375rem; /* 6px */" },
    { value: "max-h-2", label: "max-height: 0.5rem; /* 8px */" },
    { value: "max-h-2.5", label: "max-height: 0.625rem; /* 10px */" },
    { value: "max-h-3", label: "max-height: 0.75rem; /* 12px */" },
    { value: "max-h-3.5", label: "max-height: 0.875rem; /* 14px */" },
    { value: "max-h-4", label: "max-height: 1rem; /* 16px */" },
    { value: "max-h-5", label: "max-height: 1.25rem; /* 20px */" },
    { value: "max-h-6", label: "max-height: 1.5rem; /* 24px */" },
    { value: "max-h-7", label: "max-height: 1.75rem; /* 28px */" },
    { value: "max-h-8", label: "max-height: 2rem; /* 32px */" },
    { value: "max-h-9", label: "max-height: 2.25rem; /* 36px */" },
    { value: "max-h-10", label: "max-height: 2.5rem; /* 40px */" },
    { value: "max-h-11", label: "max-height: 2.75rem; /* 44px */" },
    { value: "max-h-12", label: "max-height: 3rem; /* 48px */" },
    { value: "max-h-14", label: "max-height: 3.5rem; /* 56px */" },
    { value: "max-h-16", label: "max-height: 4rem; /* 64px */" },
    { value: "max-h-20", label: "max-height: 5rem; /* 80px */" },
    { value: "max-h-24", label: "max-height: 6rem; /* 96px */" },
    { value: "max-h-28", label: "max-height: 7rem; /* 112px */" },
    { value: "max-h-32", label: "max-height: 8rem; /* 128px */" },
    { value: "max-h-36", label: "max-height: 9rem; /* 144px */" },
    { value: "max-h-40", label: "max-height: 10rem; /* 160px */" },
    { value: "max-h-44", label: "max-height: 11rem; /* 176px */" },
    { value: "max-h-48", label: "max-height: 12rem; /* 192px */" },
    { value: "max-h-52", label: "max-height: 13rem; /* 208px */" },
    { value: "max-h-56", label: "max-height: 14rem; /* 224px */" },
    { value: "max-h-60", label: "max-height: 15rem; /* 240px */" },
    { value: "max-h-64", label: "max-height: 16rem; /* 256px */" },
    { value: "max-h-72", label: "max-height: 18rem; /* 288px */" },
    { value: "max-h-80", label: "max-height: 20rem; /* 320px */" },
    { value: "max-h-96", label: "max-height: 24rem; /* 384px */" },
    { value: "max-h-full", label: "max-height: 100%;" },
    { value: "max-h-screen", label: "max-height: 100vh;" },
    { value: "max-h-min", label: "max-height: min-content;" },
    { value: "max-h-max", label: "max-height: max-content;" },
    { value: "max-h-fit", label: "max-height: fit-content;" }
  ]
};

export default [Width, MinWidth, MaxWidth, Height, MinHeight, MaxHeight];
